name: todo_list
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter_modular: ^6.3.2
  mobx: ^2.3.3+2
  mocktail: ^1.0.3
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2 
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

# Seção de assets (opcional, adicione aqui seus assets)
# assets:
#   - images/ic_launcher.png

# Seção de fonts (opcional, adicione aqui suas fonts)
# fonts:
#   - family: MyFont
#     fonts:
#       - asset: fonts/MyFont.ttf
